### ISSUE TITLE
Support Map type in params for mustache or add a new template type? 

### ISSUE THREAD

**Issue by umeshdangat** [o19s/elasticsearch-learning-to-rank#164]
If we use native scripts that are invoked by ltr using mustache, then params is an important way to pass down query_time information. If the native plugin uses POJOs which are built based of the params, the ability to build such POJOs is somewhat limited. For example if a POJO takes in a `Map`  the code to deserialize breaks, mainly because LTR uses mustache to [stringify the map](https://github.com/o19s/elasticsearch-learning-to-rank/blob/63fec96ee3d823b75479d1c93201e7d7d6caaa1e/src/main/java/com/o19s/es/template/mustache/MustacheUtils.java#L60). Would it be possible to pass down the map instead?

More explanation below:

POST a feature which invokes `native` script (another elasticsearch plugin). Notice that one of the parameters is a `Map`
```
{
  "featureset": {
    "name": "ltr_dummy_features",
    "features": [
      {
        "name": "dummy_feature",
        "params": [
          "map_field",
          "str_field"
          "int_field"
        ],
        "template_language": "mustache",
        "template": {
          "function_score": {
            "script_score": {
              "script": {
                "lang": "native",
                "source": "feature_extractor",
                "params": {
                  "map_field": "{{map_field}}",
                  "str_field": "{{str_field}}",
                  "int_field": "{{int_field}}"
                }
              }
            }
          }
        }
      }
    ]
  }
}
```

Query the feature such that the `params` is a _jsonString_
```
{
  "query": {
    "sltr": {
      "params": {
				"name": "dummy_feature",
				"type": "dummy_feature",
				"weights": {
					"11862": 0.05
				},
				"aggregation": "sum",
				"ancestors": "false"
			},
      "model": "ltr_dummy_model"
    }
  }
}
```

Errors like so:
`"reason": "Cannot construct instance of `java.util.LinkedHashMap` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('{11862=0.05}')\n at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.yelp.search.dummy.features.FeatureExtractorWrapper$DummyFeature[\"map_field\"])"`

Note that in my native plugin I try to deserialize the following using Jackson:
```
        @JsonCreator
        public DummyFeature(
                @JsonProperty("str_field") String name,
                @JsonProperty("map_field") Map<Short, Double> weights,
                @JsonProperty("int_field") int foo
        ) {
...
        }

```

Looking at the code it seems like I can workaround this by having a `setter` for `map_field` that takes in the stringifiedMap via `Map.toString()` (in mustache)  and set `map_field`. But it seems awkward to be doing this?

Would it make sense to support such a feature where the params can be nested POJOs which could take in Maps either within `mustache_template` or write a new `template` type?

@nomoa could you please let me know what you think?

**Comment by nomoa** [comment]
@umeshdangat have you tried to use `{{#toJson}}map_field{{/toJson}}` ?
See the examples in https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html.

**Comment by umeshdangat** [comment]
@nomoa thanks, that seems to be easy enough. But I still get an exception. 

```
"caused_by": {
							"type": "json_parse_exception",
							"reason": "Unexpected character ('1' (code 49)): was expecting comma to separate Object entries\n at [Source: {\"function_score\":{\"script_score\":{\"script\":{\"lang\":\"native\",\"source\":\"feature_extractor\",\"params\":{\"str_field\":\"dummy_feature\",\"int_field\":\"1\",\"map_field\":\"{\"11\":0.05}\"}}}}}; line: 1, column: 161]"
						}
```

here is the query

```
{
  "query": {
    "sltr": {
      "params": {
				"str_field": "dummy_feature",
				"int_field": 1,
				"map_field": {
					"11": 0.05
				}
			},
      "model": "ltr_dummy_model"
    }
  }
}

```

The stack trace seems to suggest its still invalid json?
```
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('1' (code 49)): was expecting comma to separate Object entries
 at [Source: {"function_score":{"script_score":{"script":{"lang":"native","source":"feature_extractor","params":{"str_field":"dummy_feature","int_field":"1","map_field":"{"11":0.05}"}}}}}; line: 1, column: 161]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702) ~[jackson-core-2.8.10.jar:2.8.10]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558) ~[jackson-core-2.8.10.jar:2.8.10]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:456) ~[jackson-core-2.8.10.jar:2.8.10]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipComma(ReaderBasedJsonParser.java:2285) ~[jackson-core-2.8.10.jar:2.8.10]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:674) ~[jackson-core-2.8.10.jar:2.8.10]
	at org.elasticsearch.common.xcontent.json.JsonXContentParser.nextToken(JsonXContentParser.java:52) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:328) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:296) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.map(AbstractXContentParser.java:251) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.common.xcontent.AbstractObjectParser.lambda$declareField$0(AbstractObjectParser.java:144) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.common.xcontent.ObjectParser.lambda$declareField$1(ObjectParser.java:214) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.common.xcontent.ObjectParser.parseValue(ObjectParser.java:314) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.common.xcontent.ObjectParser.parseSub(ObjectParser.java:325) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.common.xcontent.ObjectParser.parse(ObjectParser.java:169) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.common.xcontent.ObjectParser.apply(ObjectParser.java:183) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.script.Script.parse(Script.java:374) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.script.Script.parse(Script.java:273) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.index.query.functionscore.ScriptScoreFunctionBuilder.fromXContent(ScriptScoreFunctionBuilder.java:113) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.search.SearchModule.lambda$registerScoreFunction$4(SearchModule.java:631) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.common.xcontent.NamedXContentRegistry.parseNamedObject(NamedXContentRegistry.java:143) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.namedObject(AbstractXContentParser.java:402) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.index.query.functionscore.FunctionScoreQueryBuilder.fromXContent(FunctionScoreQueryBuilder.java:477) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.search.SearchModule.lambda$registerQuery$11(SearchModule.java:777) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.common.xcontent.NamedXContentRegistry.parseNamedObject(NamedXContentRegistry.java:143) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.namedObject(AbstractXContentParser.java:402) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.index.query.AbstractQueryBuilder.parseInnerQueryBuilder(AbstractQueryBuilder.java:313) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at com.o19s.es.ltr.feature.store.PrecompiledTemplateFeature.doToQuery(PrecompiledTemplateFeature.java:97) ~[?:?]
	at com.o19s.es.ltr.feature.store.OptimizedFeatureSet.toQueries(OptimizedFeatureSet.java:59) ~[?:?]
	at com.o19s.es.ltr.query.RankerQuery.build(RankerQuery.java:91) ~[?:?]
	at com.o19s.es.ltr.query.RankerQuery.build(RankerQuery.java:87) ~[?:?]
	at com.o19s.es.ltr.query.StoredLtrQueryBuilder.doToQuery(StoredLtrQueryBuilder.java:165) ~[?:?]
	at com.o19s.es.ltr.query.StoredLtrQueryBuilder.doToQuery(StoredLtrQueryBuilder.java:50) ~[?:?]
	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:97) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$2(QueryShardContext.java:304) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:316) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:303) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:707) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:558) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:534) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:330) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:316) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:312) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.search.SearchService$3.doRun(SearchService.java:1002) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:672) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_162]
```

**Comment by umeshdangat** [comment]
Seems like we need to `inline` the entire template as a `string` for  `toJson` to work.  Is documented as an [es issue](https://github.com/elastic/elasticsearch/issues/21648)

```
{
  "featureset": {
    "name": "ltr_dummy_features",
    "features": [
      {
        "name": "dummy_feature",
        "params": [
          "map_field"
        ],
        "template_language": "mustache",
        "template": "{\"function_score\": {\"script_score\": {\"script\": {\"lang\": \"native\", \"source\": \"feature_extractor\", \"params\": { \"int_field\": \"{{int_field}}\", \"str_field\": \"{{str_field}}\", \"map_field\": {{#toJson}}map_field{{/toJson}}}}}}}"

      }
    ]
  }
}


```
I am okay closing this issue, @nomoa do you think it is worth adding a note about this in the docs though?

**Comment by nomoa** [comment]
Thanks for testing this, yes it's a bit sad that we have to encode into a string the feature definition...
The mustache template used by the plugin should support everything that elastic supports, perhaps adding a link to the relevant elastic.co doc would be useful?

**Comment by umeshdangat** [comment]
@nomoa added the elasticsearch template link to the documentation.
