### ISSUE TITLE
demo in the program stuck

### ISSUE THREAD

**Issue by wangxilong1991** [o19s/elasticsearch-learning-to-rank#167]
##excuse me, When I was in the cloud demo, I found the program stuck, and then I looked at the source code for RankLib-2.8.jar. Modified the LambdaMART init: look at ******

----------------------------------------------------------------------------------------------------
       
![2](https://user-images.githubusercontent.com/21128422/41335094-3b8f0620-6f1a-11e8-8150-e03a1c38e739.png)

----------------------------------------------------------------------------------------------------
Repackage the program to run successfully !!!

**Have you found this problem? Is there any other problem that I solve this way?**
**I'm not sure about that**

----------------------------------------------------------------------------------------------------

>[root@master ~]# java -jar RankLib-2.8.jar -ranker 6 -train sample_judgments_wfeatures.txt -save model.txt -frate 1.0
Discard orig. features
Training data:	sample_judgments_wfeatures.txt
Feature vector representation: Dense.
Ranking method:	LambdaMART
Feature description file:	Unspecified. All features will be used.
Train metric:	ERR@10
Test metric:	ERR@10
Highest relevance label (to compute ERR): 4
Feature normalization: No
Model file: model.txt
[+] LambdaMART's Parameters:
No. of trees: 1000
No. of leaves: 10
No. of threshold candidates: 256
Min leaf support: 1
Learning rate: 0.1
Stop early: 100 rounds without performance gain on validation data
Reading feature file [sample_judgments_wfeatures.txt]... [Done.]
(3 ranked lists, 25 entries read)
Initializing... 
Exception in thread "pool-1-thread-1" Exception in thread "main" Exception in thread "pool-1-thread-2" ciir.umass.edu.utilities.RankLibError: Error in DenseDataPoint::getFeatureValue(): requesting unspecified feature, fid=2
at ciir.umass.edu.utilities.RankLibError.create(RankLibError.java:26)
at ciir.umass.edu.learning.DenseDataPoint.getFeatureValue(DenseDataPoint.java:26)
at ciir.umass.edu.learning.tree.LambdaMART.sortSamplesByFeature(LambdaMART.java:459)
at ciir.umass.edu.learning.tree.LambdaMART.sortSamplesByFeature(LambdaMART.java:567)
at ciir.umass.edu.learning.tree.LambdaMART$SortWorker.run(LambdaMART.java:585)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
**java.lang.NullPointerException**
at ciir.umass.edu.learning.tree.LambdaMART.init(LambdaMART.java:121)
at ciir.umass.edu.learning.RankerTrainer.train(RankerTrainer.java:42)
at ciir.umass.edu.eval.Evaluator.evaluate(Evaluator.java:733)
at ciir.umass.edu.eval.Evaluator.main(Evaluator.java:503)
ciir.umass.edu.utilities.RankLibError: Error in DenseDataPoint::getFeatureValue(): requesting unspecified feature, fid=1
at ciir.umass.edu.utilities.RankLibError.create(RankLibError.java:26)
at ciir.umass.edu.learning.DenseDataPoint.getFeatureValue(DenseDataPoint.java:26)
at ciir.umass.edu.learning.tree.LambdaMART.sortSamplesByFeature(LambdaMART.java:459)
at ciir.umass.edu.learning.tree.LambdaMART.sortSamplesByFeature(LambdaMART.java:567)
at ciir.umass.edu.learning.tree.LambdaMART$SortWorker.run(LambdaMART.java:585)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at `java.lang.Thread.run(Thread.java:748）

-------------------------------------------------------------------------------------------

**Comment by softwaredoug** [comment]
This appears to be a Ranklib bug, which isn't part of this project. That being said, we support a fork [RankyMcRankFace](http://github.com/o19s/rankymcrankface) if you want to send us a PR

**Comment by wangxilong1991** [comment]
ok，thanks

**Comment by lonngxiang** [comment]
> This appears to be a Ranklib bug, which isn't part of this project. That being said, we support a fork [RankyMcRankFace](https://github.com/o19s/rankymcrankface) if you want to send us a PR

use RankyMcRankFace still the same problem
