### ISSUE TITLE
Error in python3 train.py when run demo

### ISSUE THREAD

**Issue by intergret** [o19s/elasticsearch-learning-to-rank#191]
after loadFeatures in train.py, logFeatures occur the following error.  Es has already install the plugin: http://es-learn-to-rank.labs.o19s.com/ltr-1.1.0-es6.3.2.zip 

```json
GET http://XXXX:10301/tmdb/_search
{
  "size": 100,
  "query": {
    "bool": {
      "filter": [
        {
          "terms": {
            "_id": [
              "7555",
              "1370",
              "1369",
              "1368",
              "136278",
              "102947",
              "13969",
              "61645",
              "14423",
              "54156"
            ]
          }
        }
      ],
      "should": [
        {
          "sltr": {
            "_name": "logged_featureset",
            "featureset": "movie_features",
            "params": {
              "keywords": "rambo"
            }
          }
        }
      ]
    }
  },
  "ext": {
    "ltr_log": {
      "log_specs": {
        "name": "main",
        "named_query": "logged_featureset",
        "missing_as_zero": true
      }
    }
  }
}
```
```json
ERROR
{
  "error":{
    "root_cause":[
      {
        "type":"exception",
        "reason":"com.fasterxml.jackson.core.JsonGenerationException: Can not start an object, expecting field name (context: Object)"
      }
    ],
    "type":"exception",
    "reason":"com.fasterxml.jackson.core.JsonGenerationException: Can not start an object, expecting field name (context: Object)",
    "caused_by":{
      "type":"json_generation_exception",
      "reason":"Can not start an object, expecting field name (context: Object)",
      "suppressed":[
        {
          "type":"illegal_state_exception",
          "reason":"Failed to close the XContentBuilder",
          "caused_by":{
            "type":"i_o_exception",
            "reason":"Unclosed object or array found"
          }
        }
      ]
    }
  },
  "status":500
}
```

**Comment by intergret** [comment]
Caused by: com.fasterxml.jackson.core.JsonGenerationException: Can not start an object, expecting field name (context: Object)
	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:1897) ~[jackson-core-2.8.10.jar:2.8.10]
	at com.fasterxml.jackson.core.json.JsonGeneratorImpl._reportCantWriteValueExpectName(JsonGeneratorImpl.java:244) ~[jackson-core-2.8.10.jar:2.8.10]
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._verifyValueWrite(UTF8JsonGenerator.java:1033) ~[jackson-core-2.8.10.jar:2.8.10]
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeStartObject(UTF8JsonGenerator.java:313) ~[jackson-core-2.8.10.jar:2.8.10]
	at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.writeStartObject(JsonXContentGenerator.java:154) ~[elasticsearch-x-content-6.3.2.jar:6.3.2]
	at org.elasticsearch.common.xcontent.XContentBuilder.startObject(XContentBuilder.java:252) ~[elasticsearch-x-content-6.3.2.jar:6.3.2]
	at com.o19s.es.ltr.logging.LoggingSearchExtBuilder.toXContent(LoggingSearchExtBuilder.java:80) ~[?:?]
	at org.elasticsearch.search.builder.SearchSourceBuilder.toXContent(SearchSourceBuilder.java:1264) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.common.xcontent.XContentHelper.toXContent(XContentHelper.java:349) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.search.builder.SearchSourceBuilder.toString(SearchSourceBuilder.java:1525) ~[elasticsearch-6.3.2.jar:6.3.2]
	... 60 more

**Comment by softwaredoug** [comment]
I know this is almost a year later (sorry about that!) - but I am wondering what command you used to run Elasticsearch to set the logging level?

**Comment by softwaredoug** [comment]
Going to go ahead and close. Feel free to reopen if this continues to be an issue
