### ISSUE TITLE
集成es6.6.0启服务启不了

### ISSUE THREAD

**Issue by zhanghengze** [o19s/elasticsearch-learning-to-rank#310]
[2020-06-08T13:57:52,966][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [master] fatal error in thread [main], exiting
java.lang.NoSuchMethodError: org.elasticsearch.common.component.AbstractComponent.<init>(Lorg/elasticsearch/common/settings/Settings;)V
	at com.o19s.es.ltr.ranker.ranklib.RankLibScriptEngine.<init>(RankLibScriptEngine.java:49) ~[?:?]
	at com.o19s.es.ltr.LtrQueryParserPlugin.getScriptEngine(LtrQueryParserPlugin.java:149) ~[?:?]
	at org.elasticsearch.script.ScriptModule.<init>(ScriptModule.java:80) ~[elasticsearch-6.6.0.jar:6.6.0]
	at org.elasticsearch.node.Node.<init>(Node.java:361) ~[elasticsearch-6.6.0.jar:6.6.0]
	at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-6.6.0.jar:6.6.0]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.6.0.jar:6.6.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.6.0.jar:6.6.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.6.0.jar:6.6.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.6.0.jar:6.6.0]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-6.6.0.jar:6.6.0]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.6.0.jar:6.6.0]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.6.0.jar:6.6.0]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.6.0.jar:6.6.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) ~[elasticsearch-6.6.0.jar:6.6.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.6.0.jar:6.6.0]

**Comment by nathancday** [comment]
Thanks for opening this issue, looks like there is a problem with RankLib (the underlying ML library). I see you are on Elasticsearch v6.6.0 Can you confirm which version of the plugin you are using?

**Comment by zhanghengze** [comment]
你好  我现在用的6.3.1 现在可以用了 谢啦!!☆⌒(*＾-゜)v

**Comment by nathancday** [comment]
您还有问题吗？如果可以在本地构建，则此分支应适用于ES-6.6.0
https://github.com/o19s/elasticsearch-learning-to-rank/tree/es_6_6


由于我认为此问题导致 `./gradlew -clean -check` 在我的计算机上构建失败，因此我无法确定安装是否可以正常进行。
https://github.com/gradle/gradle/issues/10248
