### ISSUE TITLE
Installing LTR for Windows User

### ISSUE THREAD

**Issue by laxmimerit** [o19s/elasticsearch-learning-to-rank#317]
Hi,
How to make it support windows?
I want to run this command on windows.
```
./bin/elasticsearch-plugin install http://es-learn-to-rank.labs.o19s.com/ltr-1.2.1-es7.6.1.zip
```
Please advise.

**Comment by laxmimerit** [comment]
Update:
I had added `bin` in System Path and it is now able to recognize `elasticsearch-plugin` but now I am facing another issue while running this command.
```
elasticsearch-plugin install http://es-learn-to-rank.labs.o19s.com/ltr-1.2.1-es7.6.1.zip
```
I am getting this Error

```
-> Installing http://es-learn-to-rank.labs.o19s.com/ltr-1.2.1-es7.6.1.zip
-> Downloading http://es-learn-to-rank.labs.o19s.com/ltr-1.2.1-es7.6.1.zip
[=================================================] 100%  
-> Failed installing http://es-learn-to-rank.labs.o19s.com/ltr-1.2.1-es7.6.1.zip
-> Rolling back http://es-learn-to-rank.labs.o19s.com/ltr-1.2.1-es7.6.1.zip
-> Rolled back http://es-learn-to-rank.labs.o19s.com/ltr-1.2.1-es7.6.1.zip
Exception in thread "main" java.nio.file.AccessDeniedException: C:\Program Files\Elastic\Elasticsearch\7.6.1\plugins\.installing-13507466540764045944
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:505)
        at java.base/java.nio.file.Files.createDirectory(Files.java:689)
        at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:135)
        at java.base/java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:172)
        at java.base/java.nio.file.Files.createTempDirectory(Files.java:965)
        at org.elasticsearch.plugins.InstallPluginCommand.stagingDirectoryWithoutPosixPermissions(InstallPluginCommand.java:782)
        at org.elasticsearch.plugins.InstallPluginCommand.stagingDirectory(InstallPluginCommand.java:777)
        at org.elasticsearch.plugins.InstallPluginCommand.unzip(InstallPluginCommand.java:709)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:252)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:224)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:91)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)

```

**Comment by co2nunes** [comment]
Sorry for noise on a closed thread, but I am getting exactly the same issue on MacOS and Docker.
Can you let me know how did you fix this issue? Thanks!
