### ISSUE TITLE
Null Value Exception for LambdaMART

### ISSUE THREAD

**Issue by laxmimerit** [o19s/elasticsearch-learning-to-rank#318]
Hi,
I am trying to run `python train.py` and getting this error

```
Initializing... Exception in thread "pool-1-thread-2" Exception in thread "pool-1-thread-1" Exception in thread "main" ciir.umass.edu.utilities.RankLibError: Error in DenseDataPoint::getFeatureValue(): requesting unspecified feature, fid=1
        at ciir.umass.edu.utilities.RankLibError.create(RankLibError.java:26)
        at ciir.umass.edu.learning.DenseDataPoint.getFeatureValue(DenseDataPoint.java:26)
        at ciir.umass.edu.learning.tree.LambdaMART.sortSamplesByFeature(LambdaMART.java:485)
        at ciir.umass.edu.learning.tree.LambdaMART.sortSamplesByFeature(LambdaMART.java:593)
        at ciir.umass.edu.learning.tree.LambdaMART$SortWorker.run(LambdaMART.java:611)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
ciir.umass.edu.utilities.RankLibError: Error in DenseDataPoint::getFeatureValue(): requesting unspecified feature, fid=2
        at ciir.umass.edu.utilities.RankLibError.create(RankLibError.java:26)
        at ciir.umass.edu.learning.DenseDataPoint.getFeatureValue(DenseDataPoint.java:26)
        at ciir.umass.edu.learning.tree.LambdaMART.sortSamplesByFeature(LambdaMART.java:485)
        at ciir.umass.edu.learning.tree.LambdaMART.sortSamplesByFeature(LambdaMART.java:593)
        at ciir.umass.edu.learning.tree.LambdaMART$SortWorker.run(LambdaMART.java:611)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.NullPointerException
        at ciir.umass.edu.learning.tree.LambdaMART.init(LambdaMART.java:121)
        at ciir.umass.edu.learning.RankerTrainer.train(RankerTrainer.java:42)
        at ciir.umass.edu.eval.Evaluator.evaluate(Evaluator.java:733)
        at ciir.umass.edu.eval.Evaluator.main(Evaluator.java:503)

```

**Comment by nathancday** [comment]
Looks like the model can't find a feature: `requesting unspecified feature, fid=1`
Are you requesting are feature store that doesn't exist?

**Comment by laxmimerit** [comment]
Hi Thanks for a quick reply. I had done some debug and yes you are right. A feature is missing in file `sample_judgments_wfeatures.txt`. This file is being generated by `build_features_judgments_file(judgments_with_features, filename)` and it is not able to generate file properly. I mean to say that some features are null for some queries. For example like this
```
4	qid:1	1:3.2244816	2:3.0348003 # 521909	shirt
2	qid:1	 # 520808	shirt
3	qid:2	1:4.7033896	2:3.6954064 # 565570	pant
```

At the second line, features are not generated programmatically. When I tried to fill this feature manually and commented `build_features_judgments_file()`, it worked. 

It indicates that problem is inside `build_features_judgments_file()` .  
Can you please suggest why it is happening? and how to avoid this error?

**Comment by laxmimerit** [comment]
Hi,
Can you please suggest me any work around?

**Comment by nathancday** [comment]
For examples please check out this repo instead:
[Hello LTR](https://github.com/o19s/hello-ltr)

The examples in this repo were the inspiration for Hello LTR but are not maintained today. We will change the docs to point to Hello LTR instead.

**Comment by laxmimerit** [comment]
Thanks. Will revert you.

**Comment by laxmimerit** [comment]
You mean to say that I should follow Hello LTR instead of this repo. Right?

**Comment by nathancday** [comment]
Yep!

**Comment by laxmimerit** [comment]
Thanks.
