### ISSUE TITLE
RankLib jar error: requesting unspecified feature

### ISSUE THREAD

**Issue by kapish5467** [o19s/elasticsearch-learning-to-rank#322]
On following the documentation page , when I try to run train.py, the following error occurs -
Initializing... Exception in thread "main" ciir.umass.edu.utilities.RankLibError: Error in DenseDataPoint::getFeatureValue(): requesting unspecified feature, fid=1
        at ciir.umass.edu.utilities.RankLibError.create(RankLibError.java:26)
        at ciir.umass.edu.learning.DenseDataPoint.getFeatureValue(DenseDataPoint.java:26)
        at ciir.umass.edu.learning.tree.LambdaMART.sortSamplesByFeature(LambdaMART.java:485)
        at ciir.umass.edu.learning.tree.LambdaMART.sortSamplesByFeature(LambdaMART.java:593)
        at ciir.umass.edu.learning.tree.LambdaMART.init(LambdaMART.java:102)
        at ciir.umass.edu.learning.RankerTrainer.train(RankerTrainer.java:42)
        at ciir.umass.edu.eval.Evaluator.evaluate(Evaluator.java:733)
        at ciir.umass.edu.eval.Evaluator.main(Evaluator.java:503)

Is this a known issue or am I missing something?

**Comment by nathancday** [comment]
Sorry for the delayed response. What documentation are you referencing?

**Comment by kapish5467** [comment]
https://github.com/o19s/elasticsearch-learning-to-rank/blob/master/demo/README.md
