### ISSUE TITLE
not able to install ETL Plugin into Ubuntu Server 22.04 LTS

### ISSUE THREAD

**Issue by Prajwalmrpl** [o19s/elasticsearch-learning-to-rank#444]
"version" : {
    "number" : "6.8.23",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "4f67856",
    "build_date" : "2022-01-06T21:30:50.087716Z",
    "build_snapshot" : false,
    "lucene_version" : "7.7.3",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  }

$ sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install \
https://github.com/o19s/elasticsearch-learning-to-rank/releases/download/v1.5.4-es7.11.2/ltr-plugin-v1.5.4-es7.11.2.zip

**Showing Error as:**
-> Downloading https://github.com/o19s/elasticsearch-learning-to-rank/releases/download/v1.5.4-es7.11.2/ltr-plugin-v1.5.4-es7.11.2.zip
[=================================================] 100%   
Exception in thread "main" java.lang.IllegalArgumentException: Unknown properties in plugin descriptor: [type]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:235)
	at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:724)
	at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:803)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:786)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:232)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:217)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
ubuntu@ip-10-205-160-226:~$ sudo systemctl status elasticsearch

Any Solution for this ?

**Comment by Shibe** [comment]
Seems like your ElasticSearch version and LTR version are not the same. Try 6.8.x of the LTR plugin.
